INSERT INTO AIRPORT (ID,NAME) VALUES (0, 'AICM');
INSERT INTO AIRPORT (ID,NAME) VALUES (1, 'FIPA');
INSERT INTO AIRPORT (ID,NAME) VALUES (2, 'AIT');

INSERT INTO COUNTRY (ID,CODE,NAME,IDAEREOPUERTO) VALUES (0,'MXNA', 'MEXICO',0);
INSERT INTO COUNTRY (ID,CODE,NAME,IDAEREOPUERTO) VALUES (1,'MXNJ', 'JALISCO',1);
INSERT INTO COUNTRY (ID,CODE,NAME,IDAEREOPUERTO) VALUES (2,'MXNM', 'MONTERREY',2);

INSERT INTO LANGUAGE  (ID,CODE,NAME) VALUES (0,'ESP', 'ESPAÑOL');
INSERT INTO LANGUAGE  (ID,CODE,NAME) VALUES (1,'ENG', 'INGLES');
INSERT INTO LANGUAGE  (ID,CODE,NAME) VALUES (2,'FRA', 'FRANCES');

INSERT INTO EMPLOYEE (ID,FIRSTNAME,SURNAME,IDCOUNTRY,IDLANGUAGE) VALUES (0,'JAVIER', 'POSADAS',0,0);
INSERT INTO EMPLOYEE (ID,FIRSTNAME,SURNAME,IDCOUNTRY,IDLANGUAGE) VALUES (1,'MARIELA', 'CHAVEZ',1,1);
INSERT INTO EMPLOYEE (ID,FIRSTNAME,SURNAME,IDCOUNTRY,IDLANGUAGE) VALUES (2,'JULIO', 'MARTINEZ',2,2);