INSERT INTO AIRPORT (ID,NAME) VALUES (0, 'AICM');
INSERT INTO AIRPORT (ID,NAME) VALUES (1, 'FIPA');
INSERT INTO AIRPORT (ID,NAME) VALUES (2, 'AIT');

INSERT INTO COUNTRY (ID,CODE,NAME) VALUES (0,'MXNA', 'MEXICO');
INSERT INTO COUNTRY (ID,CODE,NAME) VALUES (1,'MXNJ', 'JALISCO');
INSERT INTO COUNTRY (ID,CODE,NAME) VALUES (2,'MXNM', 'MONTERREY');

INSERT INTO EMPLOYEE (ID,FIRSTNAME,SURNAME) VALUES (0,'JAVIER', 'POSADAS');
INSERT INTO EMPLOYEE (ID,FIRSTNAME,SURNAME) VALUES (1,'MARIELA', 'CHAVEZ');
INSERT INTO EMPLOYEE (ID,FIRSTNAME,SURNAME) VALUES (2,'JULIO', 'MARTINEZ');

INSERT INTO LANGUAGE  (ID,CODE,NAME) VALUES (0,'ESP', 'ESPAÑOL');
INSERT INTO LANGUAGE  (ID,CODE,NAME) VALUES (1,'ENG', 'INGLES');
INSERT INTO LANGUAGE  (ID,CODE,NAME) VALUES (2,'FRA', 'FRANCES');